- name: minemeld install
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: install libleveldb1v5 on Ubuntu 19
      apt:
        deb: https://mirrors.edge.kernel.org/ubuntu/pool/main/l/leveldb/libleveldb1v5_1.20-2_amd64.deb
        when:
          - ansible_distribution == 'Ubuntu'
          - ansible_distribution_major_version == '19'
        
    - name: install pre-req packages
      apt:
        pkg:
        - nginx
        - redis-server
        - librrd-dev
        state: latest

    - name: Add the MineMeld repo GPG key
      apt_key:
        id: E558CE6E39680F318F6CBFACB401E02EDD0DA1F9
        url: https://minemeld-updates.panw.io/gpg.key
        state: present

    - name: Add the MineMeld APT repo
      apt_repository:
        repo: deb [arch=amd64] http://minemeld-updates.panw.io/ubuntu xenial-minemeld main
        state: present

    - name: Create symbolic link for librrd.so
      file:
        src: librrd.so
        path: /usr/lib/x86_64-linux-gnu/librrd.so.4
        state: link

    - name: Install MineMeld
      apt:
        name: minemeld
        dpkg_options: 'force-overwrite'
        state: latest
      notify: reboot system
      
  handlers:
    - name: reboot system
      shell: shutdown -r now
